project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary for CASA0023"
  navbar:
    logo: ucl.jpg
    collapse: true
    collapse-below: lg
    background: info
    search: true
    right:
      - icon: github
  sidebar:
    style: floating
    reader-mode: true
  repo-url: https://github.com/yyjj2215/learning_diary_CASA0023
  repo-actions: [edit, issue]
  author: "Yanbo Liu"
  date: "2023/1/22"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [journal, theme-light.scss]
      dark: cyborg
  pdf:
    documentclass: scrreprt

editor: visual

